<a href="https://colab.research.google.com/github/oxedanda/avcad_final_project/blob/main/01_data_loading_and_audit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [42]:
files = {
    "agricultural_labour": "/content/Mão-de-obra agrícola (N.º) por Localização geográfica (NUTS - 2013), Tipo de mão-de-obra e Regime de duração de trabalho; Não periódica.xls",
    "agricultural_holdings_area": "/content/Superfície das explorações agrícolas (ha) por Localização geográfica (NUTS - 2013), Tipo de utilização das terras e Classes de superfície agrícola utilizada; Decenal.xls",
    "temporary_crops_holdings": "/content/Explorações agrícolas com culturas temporárias (N.º) por Localização geográfica (Região agrária_Ilha) e Tipo (culturas temporárias); Decenal.xls",
    "permanent_crops_holdings": "/content/Explorações agrícolas com culturas permanentes (N.º) por Localização geográfica (Região agrária_Ilha), Tipo (culturas permanentes) e Classes de área (cultura agrícola); Decenal.xls",
    "permanent_grasslands_area": "/content/Superfície de prados e pastagens permanentes (ha) por Localização geográfica (NUTS - 2013) e Classes de área (cultura agrícola); Não periódica.xls",
    "crop_productivity": "/content/Produtividade das principais culturas agrícolas (kg_ha) por Localização geográfica (NUTS - 2013) e Espécie; Anual.xls",
}

In [81]:
# Agricultural labour

import pandas as pd

agricultural_labour = pd.DataFrame([
    {
        "year": 2019,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural labour": 596938
    },
    {
        "year": 2009,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural labour": 649607
    },
    {
        "year": 1999,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural labour": 1002480
    },
    {
        "year": 1989,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural labour": 1449906
    }
])

display(agricultural_labour)

   year geographic_location code  Agricultural labour
0  2019          Continente    1               596938
1  2009          Continente    1               649607
2  1999          Continente    1              1002480
3  1989          Continente    1              1449906

In [80]:
# Agricultural holdings area

import pandas as pd

agricultural_holdings_area = pd.DataFrame([
    {
        "year": 2019,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural holdings area (ha)": 4987658
    },
    {
        "year": 2009,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural holdings area (ha)": 4571531
    },
    {
        "year": 1999,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural holdings area (ha)": 5039569
    },
    {
        "year": 1989,
        "geographic_location": "Continente",
        "code": "1",
        "Agricultural holdings area (ha)": 5157213
    }
])

display(agricultural_holdings_area)

   year geographic_location code  Agricultural holdings area (ha)
0  2019          Continente    1                          4987658
1  2009          Continente    1                          4571531
2  1999          Continente    1                          5039569
3  1989          Continente    1                          5157213

In [77]:
# Temporary crops holdings

import pandas as pd
import numpy as np

temporary_crops_holdings = pd.DataFrame([
    {
        "year": 2019,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 124902,
        "Grain cereals": 66584,
        "Dried pulses for grain": 15945,
        "Temporary meadows": 14066,
        "Forage crops": 65416,
        "Potatoes": 34570,
        "Sugar beet": np.nan,
        "Industrial crops": 1147,
        "Horticultural crops": 15874,
        "Flowers and ornamental plants": 1005,
        "Other temporary crops": 1718
    },
    {
        "year": 2009,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 165265,
        "Grain cereals": 108524,
        "Dried pulses for grain": 28882,
        "Temporary meadows": 13293,
        "Forage crops": 102983,
        "Potatoes": 56969,
        "Sugar beet": np.nan,
        "Industrial crops": 1364,
        "Horticultural crops": 18141,
        "Flowers and ornamental plants": 1056,
        "Other temporary crops": 1424
    },
    {
        "year": 1999,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 280214,
        "Grain cereals": 190446,
        "Dried pulses for grain": 87021,
        "Temporary meadows": 19531,
        "Forage crops": 180000,
        "Potatoes": 163360,
        "Sugar beet": 495,
        "Industrial crops": 3738,
        "Horticultural crops": 48610,
        "Flowers and ornamental plants": 1744,
        "Other temporary crops": 20662
    },
    {
        "year": 1989,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 446915,
        "Grain cereals": 352158,
        "Dried pulses for grain": 222230,
        "Temporary meadows": 40645,
        "Forage crops": 285468,
        "Potatoes": 312443,
        "Sugar beet": 33,
        "Industrial crops": 3638,
        "Horticultural crops": 77052,
        "Flowers and ornamental plants": 1788,
        "Other temporary crops": 65133
    }
])

display(temporary_crops_holdings)
temporary_crops_holdings.to_csv("/content/temporary_crops_holdings_clean.csv", index=False)

,year,geographic_location,code,Total,Grain cereals,Dried pulses for grain,Temporary meadows,Forage crops,Potatoes,Sugar beet,Industrial crops,Horticultural crops,Flowers and ornamental plants,Other temporary crops
0,2019,Continente,1,124902,66584,15945,14066,65416,34570,NaN,1147,15874,1005,1718
1,2009,Continente,1,165265,108524,28882,13293,102983,56969,NaN,1364,18141,1056,1424
2,1999,Continente,1,280214,190446,87021,19531,180000,163360,495.0,3738,48610,1744,20662
3,1989,Continente,1,446915,352158,222230,40645,285468,312443,33.0,3638,77052,1788,65133

In [78]:
# Permanent crops holdings

import pandas as pd

permanent_crops_holdings = pd.DataFrame([
    {
        "year": 2019,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 205208
    },
    {
        "year": 2009,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 225806
    },
    {
        "year": 1999,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 320484
    },
    {
        "year": 1989,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 453441
    }
])

display(permanent_crops_holdings)
permanent_crops_holdings.to_csv("/content/permanent_crops_holdings_clean.csv", index=False)

   year geographic_location code   Total
0  2019          Continente    1  205208
1  2009          Continente    1  225806
2  1999          Continente    1  320484
3  1989          Continente    1  453441

In [75]:
# Permanent grasslands area

import pandas as pd

permanent_grasslands_area = pd.DataFrame([
    {
        "year": 2019,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 2003795,
        "<0.5 ha": 4081,
        "0.5 - <1 ha": 9103,
        "1 - <2 ha": 21202,
        "2 - <5 ha": 46055,
        "5 - <20 ha": 117202,
        "20 - <50 ha": 137036,
        "50 - <100 ha": 195112,
        ">= 100 ha": 1474004
    },
    {
        "year": 2009,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 1721587,
        "<0.5 ha": 4682,
        "0.5 - <1 ha": 9282,
        "1 - <2 ha": 19592,
        "2 - <5 ha": 42963,
        "5 - <20 ha": 104183,
        "20 - <50 ha": 106250,
        "50 - <100 ha": 127661,
        ">= 100 ha": 1306976
    },
    {
        "year": 1999,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 1331033,
        "<0.5 ha": 6233,
        "0.5 - <1 ha": 11087,
        "1 - <2 ha": 22782,
        "2 - <5 ha": 50696,
        "5 - <20 ha": 111410,
        "20 - <50 ha": 92054,
        "50 - <100 ha": 111249,
        ">= 100 ha": 925523
    },
    {
        "year": 1989,
        "geographic_location": "Continente",
        "code": "1",
        "Total": 754825,
        "<0.5 ha": 7128,
        "0.5 - <1 ha": 11360,
        "1 - <2 ha": 23483,
        "2 - <5 ha": 50412,
        "5 - <20 ha": 75617,
        "20 - <50 ha": 60658,
        "50 - <100 ha": 64644,
        ">= 100 ha": 461523
    }
])

display(permanent_grasslands_area)
permanent_grasslands_area.to_csv("/content/permanent_grasslands_area_clean.csv", index=False)

,year,geographic_location,code,Total,<0.5 ha,0.5 - <1 ha,1 - <2 ha,2 - <5 ha,5 - <20 ha,20 - <50 ha,50 - <100 ha,>= 100 ha
0,2019,Continente,1,2003795,4081,9103,21202,46055,117202,137036,195112,1474004
1,2009,Continente,1,1721587,4682,9282,19592,42963,104183,106250,127661,1306976
2,1999,Continente,1,1331033,6233,11087,22782,50696,111410,92054,111249,925523
3,1989,Continente,1,754825,7128,11360,23483,50412,75617,60658,64644,461523

In [79]:
# Crop productivity

import pandas as pd
import numpy as np

crop_productivity = pd.DataFrame([
    {
        "year": 2019,
        "geographic_location": "Continente",
        "code": "1",
        "Cereals for grain": 5160,
        "Main dried legumes": 797,
        "Potatoes": 22953,
        "Main crops for industry": 65754,
        "Horticultural crops": np.nan,
        "Main fodder crops": 28241,
        "Main fresh fruits": 15451,
        "Small berries": 10508,
        "Main subtropical fruits": 10690,
        "Citrus fruits": 19460,
        "Main nut fruits": 772,
        "Vineyards": 4948,
        "Olive groves": 2481
    },
    {
        "year": 2009,
        "geographic_location": "Continente",
        "code": "1",
        "Cereals for grain": 3290,
        "Main dried legumes": 549,
        "Potatoes": 15566,
        "Main crops for industry": 35105,
        "Horticultural crops": np.nan,
        "Main fodder crops": 13726,
        "Main fresh fruits": np.nan,
        "Small berries": 17471,
        "Main subtropical fruits": 11924,
        "Citrus fruits": 580,
        "Main nut fruits": 4340,
        "Vineyards": 1229,
        "Olive groves": 2795
    }
])

display(crop_productivity)

,year,geographic_location,code,Cereals for grain,Main dried legumes,Potatoes,Main crops for industry,Horticultural crops,Main fodder crops,Main fresh fruits,Small berries,Main subtropical fruits,Citrus fruits,Main nut fruits,Vineyards,Olive groves
0,2019,Continente,1,5160,797,22953,65754,NaN,28241,15451.0,10508,10690,19460,772,4948,2481
1,2009,Continente,1,3290,549,15566,35105,NaN,13726,NaN,17471,11924,580,4340,1229,2795